.rubocop.yml
Gemfile.lock
lib/workos/profile.rb
spec/lib/workos/sso_spec.rb
workos.gemspec

Just a couple things for cleanup here. 
I'm hoping that this will allow us to release 0.0.2 on rubygems via semaphore, but i keep running into issues there
@maxchehab is working on some breaking changes, and we have customers who are installing from github, so need to get it cut to rubygems and have folks update their Gemfiles before merging that work

some dependency updates, rule changes

---

README.md

Takes the getting started and SSO docs from the docs site and copies to README.
I didn't include anything concerning contributing or building from source, do we think we need docs like that here?

copy mdx docs to README

---

Gemfile.lock
docs/WorkOS.html
docs/WorkOS/APIError.html
docs/WorkOS/AuditLog.html
docs/WorkOS/AuthenticationError.html
docs/WorkOS/Base.html
docs/WorkOS/Client.html
docs/WorkOS/InvalidRequestError.html
docs/WorkOS/Profile.html
docs/WorkOS/SSO.html
docs/WorkOS/Types.html
docs/WorkOS/Types/ProfileStruct.html
docs/WorkOS/Types/Provider.html
docs/WorkOS/WorkOSError.html
docs/file.README.html
docs/index.html
docs/method_list.html
docs/top-level-namespace.html
lib/workos.rb
lib/workos/base.rb
lib/workos/client.rb
lib/workos/errors.rb
lib/workos/sso.rb
lib/workos/types.rb
lib/workos/types/provider_enum.rb
lib/workos/version.rb
spec/lib/workos/sso_spec.rb

v low priority here. mostly wanted to get your 👀 here for finding a better naming approach. I think that until we move further forward with IdP Link embed we'll not cut a new gem version, but this is for the ability to demo.

Add DraftConnection support

---

docs/WorkOS.html
docs/WorkOS/APIError.html
docs/WorkOS/AuditLog.html
docs/WorkOS/AuthenticationError.html
docs/WorkOS/Base.html
docs/WorkOS/Client.html
docs/WorkOS/InvalidRequestError.html
docs/WorkOS/Profile.html
docs/WorkOS/SSO.html
docs/WorkOS/Types.html
docs/WorkOS/Types/ProfileStruct.html
docs/WorkOS/Types/Provider.html
docs/WorkOS/WorkOSError.html
docs/file.README.html
docs/index.html
docs/top-level-namespace.html
lib/workos/sso.rb

This PR updates references to IdP Link to WorkOS.js

Update comments referencing IdP Link to WorkOS.js

---

Gemfile.lock
docs/WorkOS.html
docs/WorkOS/APIError.html
docs/WorkOS/AuditTrail.html
docs/WorkOS/AuthenticationError.html
docs/WorkOS/Base.html
docs/WorkOS/Client.html
docs/WorkOS/InvalidRequestError.html
docs/WorkOS/Profile.html
docs/WorkOS/SSO.html
docs/WorkOS/Types.html
docs/WorkOS/Types/ProfileStruct.html
docs/WorkOS/Types/Provider.html
docs/WorkOS/WorkOSError.html
docs/file.README.html
docs/index.html
docs/top-level-namespace.html
lib/workos/version.rb

bump version; update docs

---

README.md
lib/workos.rb

Update env var to match other SDKs

update env var

---

lib/workos/version.rb

bump version

---

Gemfile.lock
lib/workos.rb
lib/workos/directory_sync.rb
spec/lib/workos/directory_sync_spec.rb
spec/support/fixtures/vcr_cassettes/directory_sync/get_group.yml
spec/support/fixtures/vcr_cassettes/directory_sync/get_group_with_invalid_id.yml
spec/support/fixtures/vcr_cassettes/directory_sync/get_user.yml
spec/support/fixtures/vcr_cassettes/directory_sync/get_user_with_invalid_id.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_directories.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_directories_with_domain_param.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_groups.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_groups_with_directory_param.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_users.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_users_with_directory_param.yml

Adds a `WorkOS::DirectorySync` module with convenience methods for accessing directory endpoints.

add Directory Sync support

---

workos.gemspec

Add `documentation_uri` and reformat

add documentation_uri

---

Gemfile.lock
lib/workos/sso.rb
spec/lib/workos/sso_spec.rb

change type

---

Gemfile.lock
lib/workos/profile.rb
lib/workos/types/profile_struct.rb

Profile `first_name` and `last_name` should be nilable since we cannot guarantee an authenticating user contains both attributes.

change struct

---

Gemfile.lock
lib/workos/audit_trail.rb
lib/workos/version.rb
spec/lib/workos/audit_trail_spec.rb
spec/support/fixtures/vcr_cassettes/audit_trail/get_events.yml

* Adding the ability to fetch Audit Trail events via the Ruby SDK.
* Bump gem version to 0.4.0

Support for GET /events endpoint

---

lib/workos.rb
lib/workos/organization.rb
lib/workos/portal.rb
lib/workos/types.rb
lib/workos/types/organization_struct.rb
spec/lib/workos/portal_spec.rb
spec/support/fixtures/vcr_cassettes/organization/create.yml
spec/support/fixtures/vcr_cassettes/organization/create_invalid.yml

* Adds the ability to create an organization via the SDK for use
with the Admin Portal.

Add WorkOS::Portal.create_organization

---

lib/workos/portal.rb
lib/workos/types.rb
lib/workos/types/intent_enum.rb
spec/lib/workos/portal_spec.rb
spec/support/fixtures/vcr_cassettes/portal/generate_link.yml
spec/support/fixtures/vcr_cassettes/portal/generate_link_invalid.yml

* Adds an SDK method to generate an Admin Portal link.

Add WorkOS::Portal.generate_link

---

Gemfile.lock
lib/workos/version.rb

* This release contains SDK methods to interact with the WorkOS
Admin Portal.

Bump gem to 0.6.0

---

Gemfile.lock
lib/workos/types.rb
lib/workos/version.rb
workos.gemspec

Added in #53 unfortunately this ran into a path issue when the gem was used externally in another app and was not caught by our tests.

Revert require all

---

lib/workos/sso.rb
spec/lib/workos/sso_spec.rb
spec/support/fixtures/vcr_cassettes/sso/list_connections.yml
spec/support/fixtures/vcr_cassettes/sso/list_connections_with_after_param.yml
spec/support/fixtures/vcr_cassettes/sso/list_connections_with_before_param.yml
spec/support/fixtures/vcr_cassettes/sso/list_connections_with_connection_type_param.yml
spec/support/fixtures/vcr_cassettes/sso/list_connections_with_domain_param.yml
spec/support/fixtures/vcr_cassettes/sso/list_connections_with_limit_param.yml

Added a API call for GET /connections + tests

Add GET /connections support

---

lib/workos/sso.rb
spec/lib/workos/sso_spec.rb
spec/support/fixtures/vcr_cassettes/sso/get_connection_with_invalid_id.yml
spec/support/fixtures/vcr_cassettes/sso/get_connection_with_valid_id.yml

Second pass without the sensitive information. I messed up something with git in the last one 🤦‍♀️ and deleted all the mentions of the sensitive info.

Add GET /connections/:id support

---

lib/workos/client.rb
lib/workos/sso.rb
spec/lib/workos/sso_spec.rb
spec/support/fixtures/vcr_cassettes/sso/delete_connection_with_invalid_id.yml
spec/support/fixtures/vcr_cassettes/sso/delete_connection_with_valid_id.yml

Adds support for the Delete /connections/:id API endpoint

Add delete /connections/:id endpoint

---

Gemfile.lock
lib/workos/sso.rb
lib/workos/version.rb
spec/lib/workos/sso_spec.rb
spec/support/fixtures/vcr_cassettes/sso/list_connections_with_organization_id_param.yml

Adds organization id parameter to the list connections API

Add organization id param to list connections API

---

lib/workos/directory_sync.rb
spec/lib/workos/directory_sync_spec.rb
spec/support/fixtures/vcr_cassettes/directory_sync/delete_directory.yml

Adds a delete directory endpoint and a corresponding test.

Add delete directory endpoint

---

.semaphore/semaphore.yml

I forgot to add this in my version bump PR

Add CI test for ruby 3.0.1

---

Gemfile.lock
lib/workos/version.rb

Bumps minor version of SDK to 0.11.0

Bump minor version to 0.11.0

---

Gemfile.lock
lib/workos/directory_user.rb
lib/workos/types/directory_user_struct.rb
lib/workos/version.rb

Exposes the idp_id field for Directory Users and bumps version to 0.11.1.

Expose idp_id for directory users

---

lib/workos/client.rb
lib/workos/portal.rb
spec/lib/workos/portal_spec.rb
spec/support/fixtures/vcr_cassettes/organization/update.yml
spec/support/fixtures/vcr_cassettes/organization/update_invalid.yml

Adds an update organization method

Add update organization API endpoint

---

lib/workos/portal.rb
spec/lib/workos/portal_spec.rb
spec/support/fixtures/vcr_cassettes/organization/get.yml
spec/support/fixtures/vcr_cassettes/organization/get_invalid.yml

Adds a method to GET an organization by ID

Add GET /organizations/:id endpoint method

---

Gemfile.lock
lib/workos/connection.rb
lib/workos/types/connection_struct.rb
lib/workos/version.rb
spec/lib/workos/sso_spec.rb
spec/support/fixtures/vcr_cassettes/sso/create_connection_with_valid_source.yml

- Support both connection status to state

Update connection status to state

---

.semaphore/semaphore.yml
lib/workos/client.rb
lib/workos/profile.rb
lib/workos/profile_and_token.rb
lib/workos/sso.rb
spec/lib/workos/sso_spec.rb
spec/support/fixtures/vcr_cassettes/sso/profile.yml

* Adds a method to retreive a profile with an access token.
* Adds to ability to use access tokens as a Bearer token in place of
an API key.

Add WorkOS::SSO#get_profile

---

Gemfile.lock
lib/workos/version.rb

Bumps patch version to release bug fix

Bump patch version to 1.2.1

---

lib/workos/directory_user.rb
lib/workos/types/directory_user_struct.rb

Supports the groups attribute for a directory user.

Support groups attribute for directory user

---

Gemfile.lock
lib/workos/version.rb

- Bump addressable from 2.7.0 to 2.8.0
- Add Microsoft OAuth provider enum

Bump minor version to 1.4.0

---

lib/workos/directory_user.rb
lib/workos/types/directory_user_struct.rb
spec/lib/workos/directory_sync_spec.rb
spec/support/fixtures/vcr_cassettes/directory_sync/get_user.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_users/with_after.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_users/with_before.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_users/with_directory.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_users/with_group.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_users/with_limit.yml

Adds custom_attributes field for directory users.

Support custom_attributes for directory users

---

Gemfile.lock
lib/workos/version.rb

- Add `custom_attributes` for directory users: https://github.com/workos-inc/workos-ruby/pull/119
- Add `created_at` and `updated_at` attributes for connections, organizations, and directories: https://github.com/workos-inc/workos-ruby/pull/120

Bump minor version to 1.5.0

---

Gemfile.lock
lib/workos/version.rb

* Better thread safety with `Net::HTTP`: #110

Bump patch version to 1.5.1

---

lib/workos/directory.rb
lib/workos/types/directory_struct.rb
spec/lib/workos/directory_sync_spec.rb
spec/support/fixtures/vcr_cassettes/directory_sync/list_directories/with_after.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_directories/with_before.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_directories/with_domain.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_directories/with_limit.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_directories/with_no_options.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_directories/with_search.yml

Makes directory `domain` parameter nullable, as we're pulling this from the organization's domains which can be empty.

Make directory domain nullable

---

lib/workos/directory_sync.rb
spec/lib/workos/directory_sync_spec.rb
spec/support/fixtures/vcr_cassettes/directory_sync/get_directory_with_invalid_id.yml
spec/support/fixtures/vcr_cassettes/directory_sync/get_directory_with_valid_id.yml

Adds method to get a directory by ID

Add method to get a directory

---

lib/workos/directory_sync.rb

Add ability to list directories by organization id

Add organization Id filter to list directories method

---

lib/workos/directory_group.rb
lib/workos/types/directory_group_struct.rb
spec/lib/workos/directory_sync_spec.rb
spec/support/fixtures/vcr_cassettes/directory_sync/get_group.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_groups/with_after.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_groups/with_before.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_groups/with_directory.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_groups/with_limit.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_groups/with_no_options.yml
spec/support/fixtures/vcr_cassettes/directory_sync/list_groups/with_user.yml

Adds the following attributes to the directory group: `idp_id`, `directory_id`, `created_at`, `updated_at`, and `raw_attributes`

Add missing attributes to directory group interface

---

lib/workos/directory_user.rb
spec/lib/workos/directory_user_spec.rb

Adds method on the directory user class to get the primary email out of the email array.

Add getter method for directory user primary email

---

Gemfile.lock
lib/workos/version.rb

https://github.com/workos/workos-ruby/pull/169

Bump version to 2.5.1

---

lib/workos/events.rb
spec/support/fixtures/vcr_cassettes/events/list_events_with_after.yml
spec/support/fixtures/vcr_cassettes/events/list_events_with_event.yml
spec/support/fixtures/vcr_cassettes/events/list_events_with_no_options.yml
spec/support/fixtures/vcr_cassettes/events/list_events_with_range.yml

Updating the `list_metadata` response to the correct value from the API
```
[ ] Yes
```

Use `list_metadata` for Events

---

lib/workos.rb
lib/workos/types.rb
lib/workos/types/user_struct.rb
lib/workos/user.rb
lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/get_user.yml

* Bootstraps the UserManagement module as this is the first method in it.
```
[ ] Yes
```

Add get_user method to UserManagement module

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/list_users/no_options.yml
spec/support/fixtures/vcr_cassettes/user_management/list_users/with_options.yml

* Returns a list of users that match the provided options
```
[ ] Yes
```

Add list_users method to UserManagement module

---

.gitignore
lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/create_user_invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/create_user_valid.yml

* Creates a user with the provided parameters
```
[ ] Yes
```

Add create_user method to UserManagement module

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/remove_user_from_organization_invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/remove_user_from_organization_valid.yml

* Removes a User as a member of the given Organization.
```
[ ] Yes
```

Add remove_user_from_organization method to UserManagement module

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/send_verification_email/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/send_verification_email/valid.yml

* Sends a verification email to the provided users.
```
[ ] Yes
```

Add send_verification_email method to UserManagement module

---

lib/workos.rb
lib/workos/user_and_token.rb
lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/create_password_reset_challenge/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/create_password_reset_challenge/valid.yml

* Creates a password reset challenge and emails a password reset link to a user.
```
[ ] Yes
```

Add create_password_reset_challenge method to UserManagement module

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/add_user_to_organization_invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/add_user_to_organization_valid.yml

* Adds a User as a member of the given Organization.
```
[ ] Yes
```

Add add_user_to_organization method to UserManagement module

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/send_verification_email/valid.yml

Change return type of send_verification_email to MagicAuthChallenge

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/confirm_password_reset/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/confirm_password_reset/valid.yml

* Resets user password using token that was sent to the user.
```
[ ] Yes
```

Add complete_password_reset method to UserManagement module

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/verify_email/invalid_code.yml
spec/support/fixtures/vcr_cassettes/user_management/verify_email/invalid_magic_auth_challenge.yml
spec/support/fixtures/vcr_cassettes/user_management/verify_email/valid.yml

* Verifies user email using one-time code that was sent to the user.
```
[ ] Yes
```

Add verify_email method to UserManagement module

---

lib/workos.rb
lib/workos/authentication_response.rb
lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/authenticate_user_password/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_user_password/valid.yml

Adds authenticate_user_password as well as AuthenticationResponse object to handle nested user object.
```
[ ] Yes
```

Add authenticate_user_password method to UserManagement module

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/authenticate_user_with_totp/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_user_with_totp/valid.yml

Add functionality to authenticate a user using `TOTP` 
```
[X] Yes
```

Add authenticate with TOTP method

---

lib/workos/types/provider_enum.rb
lib/workos/user_management.rb
spec/lib/workos/sso_spec.rb
spec/lib/workos/user_management_spec.rb

Add GitHub provider

---

lib/workos/types/provider_enum.rb
spec/lib/workos/sso_spec.rb

Add GitHub provider (v2.x)

---

lib/workos/version.rb

Bump version to v2.17.0

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_organization_selection/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_organization_selection/valid.yml

Add authenticate_with_organization_selection to UserManagement
See api reference https://workos.com/docs/reference/user-management/authentication/organization-selection
```
[ ] Yes
```

Add authenticate_with_organization_selection to UserManagement

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb

Rename id param in send_verification_email function
```
[ ] Yes
```

Rename id param in send_verification_email function

---

.semaphore/semaphore.yml

chore: update image

---

.semaphore/rubygems.yml

Same change as #267, but ported to the `rubygems.yml` configuration.
```
[ ] Yes
```

Update `os_image` for `rubygems` workflow

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/deactivate_organization_membership.yml
spec/support/fixtures/vcr_cassettes/user_management/list_organization_memberships/with_statuses_option.yml
spec/support/fixtures/vcr_cassettes/user_management/reactivate_organization_membership.yml

Add organization membership deactivate and reactivate API methods.
```
[x] Yes
```

Add organization membership deactivate and reactivate API methods

---

Gemfile.lock
lib/workos/version.rb

Bump to version 4.6.0.
```
[ ] Yes
```

Bump to version 4.6.0

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/find_invitation_by_token/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/find_invitation_by_token/valid.yml

Exposes find invitation by token method
```
[x] Yes
```
https://github.com/workos/workos/pull/27785

Add find invitation by token method

---

Gemfile.lock
lib/workos/user_management.rb
lib/workos/version.rb
spec/lib/workos/user_management_spec.rb

feat: add support for totp_secret

---

Gemfile.lock
lib/workos/version.rb

Major bump to version 5.0.0.
```
[ ] Yes
```

Major bump to version 5.0.0

---

spec/lib/workos/event_spec.rb
spec/support/fixtures/vcr_cassettes/events/list_events_with_organization_id.yml

Add missing events parameter to test.
```
[ ] Yes
```

Add missing events parameter to test

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/update_organization_membership/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/update_organization_membership/valid.yml

Fix syntax on `update_organization_membership` and tests

---

Gemfile.lock
lib/workos/version.rb

Bumps version.
```
[ ] Yes
```

Update version to 5.7.0

---

Gemfile.lock
lib/workos/version.rb

Minor version bump to release #330 
```
[ ] Yes
```

Bump minor version 5.8.0

---

Gemfile.lock
lib/workos/version.rb

Bump to version 5.9.0.
```
[ ] Yes
```

Bump to version 5.9.0

---

Gemfile.lock
lib/workos/version.rb

Bump to version 5.16.0 to add `email` field to DirectoryUser.
```
[ ] Yes
```

Bump to version 5.16.0

---

.rubocop.yml
lib/workos/client.rb
lib/workos/mfa.rb
lib/workos/session.rb
lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/update_user/email.yml

Allows updating a user's email in `update_user`.
```
[X] Yes
```

Support `email` param in `update_user`
