workos/workos-ruby

lib/workos/sso.rb
spec/lib/workos/sso_spec.rb

https://app.clubhouse.io/workos/story/1178/ruby-attach-the-request-id-to-relevant-sdk-exceptions
---
Pretty simple! Couple of lines + a spec.
`Net::HTTP` is a little odd in the sense that it downcases headers. All good though:
```ruby
irb(main):015:0>   profile = WorkOS::SSO.profile(
irb(main):016:1*     code: 'foo',
irb(main):017:1*     project_id: PROJECT_ID,
irb(main):018:1*     redirect_uri: REDIRECT_URI
irb(main):019:1>   )
...
WorkOS::RequestError (The code 'foo' has expired or is invalid. - request ID: 7423a232-c8d7-41b5-bb2e-375d6919a019)
```
Totally open to suggestions wrt to the formatting or copy of adding the request ID to the error message. Ruby exceptions just take a string message, nothing formatted like key / value.
@mark I figure this `client` method will become a …

Attach the Request ID to relevant SDK exceptions

---

README.md
codecov.yml
lib/workos/sso.rb
spec/lib/workos/sso_spec.rb

https://app.clubhouse.io/workos/story/1162/add-ruby-sdk-version-to-user-agent-header
---
Adds the `'X-SDK-VERSION'` header to outgoing requests (just profile for now with SSO).
Is that the best name for the header?
EDIT:
This now puts the version and some other info (ruby version, ruby platform) in the User Agent:
```
'User-Agent'=>'WorkOS; ruby/2.6.5; x86_64-darwin18; v0.0.2'
```
I cribbed the method from another gem that seemed legit!
I've also removed codecov "patch" checking and added the badge to the README

Add version header to Ruby SDK requests

---

lib/workos/sso.rb
spec/lib/workos/sso_spec.rb

This changes the `profile` request to use the `POST` body instead of query parameters.

[feature] move query params to body

---

README.md

The current link in the `README.md` gives a 404

Fix link to Audit Trail Idempotency documentation in `README.md`

---

Gemfile.lock
lib/workos/directory_sync.rb
lib/workos/version.rb

* Encountered an issue in a simple example Sinatra app where calling
`WorkOS::DirectorySync.list_directories` would encounter an issue
with `Net` being an undefined constant. Adding this require resolves
the issue.
* Bump gem to 0.4.1
```
NameError - uninitialized constant Net
Did you mean?  Set:
/Users/willman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/workos-0.4.0/lib/workos/client.rb:45:in `get_request'
```

Require 'net/http' from WorkOS::DirectorySync

---

lib/workos.rb
lib/workos/portal.rb
lib/workos/types.rb
lib/workos/types/list_struct.rb
spec/lib/workos/portal_spec.rb
spec/support/fixtures/vcr_cassettes/organization/list.yml

* Returns a list of the organizations accessible to the provided
API key. Includes pagination functionality via the list_metadata
property.

Add WorkOS::Portal.list_organizations

---

lib/workos/portal.rb

* Modifies the arg to accept an array of strings, instead of a
string.

Rename list_organizations arg "domain" to "domains"

---

lib/workos/audit_trail.rb

This PR lists the `occurred_at_lte` option for the `get_events` method.

Add missing option `occurred_at_lte`

---

lib/workos.rb
lib/workos/client.rb
lib/workos/passwordless.rb
lib/workos/types.rb
lib/workos/types/passwordless_session_struct.rb
spec/lib/workos/passwordless_spec.rb
spec/support/fixtures/vcr_cassettes/passwordless/create_session.yml
spec/support/fixtures/vcr_cassettes/passwordless/create_session_invalid.yml
spec/support/fixtures/vcr_cassettes/passwordless/send_session.yml
spec/support/fixtures/vcr_cassettes/passwordless/send_session_invalid.yml

Add Passwordless support for MagicLink. Adds two methods
- `create_session` - generate a passwordless session for a user from their email
- `send_session` - send an email to a user with a Magic Link confirmation URL

Add MagicLink support through Passwordless module

---

Gemfile.lock
lib/workos/types.rb
workos.gemspec

* Resolves a hidden step needed before adding a file to the types
folder that can be confusing for developers new to the SDK
codebase.
* Discussion here: https://github.com/workos-inc/workos-ruby/pull/48#discussion_r485866330

Use require_all to pull in types folder

---

Gemfile.lock
lib/workos/portal.rb
lib/workos/version.rb

* An issue in our earlier implementation was returning the raw
response without wrapping it in our helper object. This commit makes
the breaking change to now return the WorkOS::Organization instance
automatically.
* Bump to 0.8.0

Return a collection of WorkOS::Organization from list_organizations

---

Gemfile.lock
lib/workos/version.rb

Increasing the SDK minor version to include my recent updates to the tests and docs. This highlights the support for the `redirect_uri` in the passwordless auth API endpoint.

Bump SDK minor version to 0.9.1

---

lib/workos/audit_trail.rb

Before this change, I received 401 responses.
After this change, the request was a success.
Example program:
```ruby
require 'date'
require 'json'
require 'workos'
WorkOS.key = ENV.fetch('WORKOS_API_KEY')
event = {
action_type: 'r',
action: 'user.login_succeeded',
actor_id: 'user_01DEQWZNQT8Y47HDPSJKQS1J3F',
actor_name: 'WorkOS Ruby Gem Test',
group: 'foo-corp.com',
latitude: '40.676300',
longitude: '-73.949200',
location: '65.215.8.114',
occurred_at: DateTime.now.iso8601,
target_id: 'user_01DEQWZNQT8Y47HDPSJKQS1J3F',
target_name: 'WorkOS Ruby Gem Test'
}
WorkOS::AuditTrail.create_event(event: event)
```

Authenticate POST /events endpoint

---

Gemfile.lock
lib/workos/version.rb

New release with:
- Audit Trail POST /events bug fix
- Require JSON gem for entire WorkOS module

Bump SDK minor version to 0.9.2

---

spec/lib/workos/audit_trail_spec.rb
spec/lib/workos/directory_sync_spec.rb
spec/lib/workos/passwordless_spec.rb
spec/lib/workos/portal_spec.rb
spec/lib/workos/sso_spec.rb
spec/spec_helper.rb

* The majority of the time our test suite does not need to make live
requests against the API. We want to avoid this step where we set
API keys in setup blocks to make requests. If you need to make a
request (for example, setting up a new VCR cassette) run:
WORKOS_API_KEY=<key> rspec

Add blocks of code setting WorkOS.key per test

---

lib/workos/passwordless.rb

The Create Passwordless Session method supports an options Hash, so I added a description of the connection parameter to the comments describing the options hash.

Add description of connection param in comments

---

lib/workos/sso.rb
spec/lib/workos/sso_spec.rb

This PR removes support for the deprecated `project_id` parameter.
This is a breaking change that will be part of `v1.0.0`.
Resolves SDK-162.

Remove support for deprecated `project_id` parameter

---

lib/workos/errors.rb
lib/workos/sso.rb
spec/lib/workos/sso_spec.rb

The Ruby SDK currently only supports a `message` in the body of an error, however the API sends an `error` and `error_description` in some error bodies.
We should support both in the error handling.
@maxdeviant this is a first pass at improving the error handling. Let me know if you have thoughts on how to implement it better. Additionally, will all errors that have an `error` in the body also have an `error_description`? Or should we account for the case where there is an `error` but no `error_description`?

Support error and error description in the body of an error

---

lib/workos/client.rb
spec/lib/workos/audit_trail_spec.rb
spec/lib/workos/directory_sync_spec.rb
spec/lib/workos/organizations_spec.rb
spec/lib/workos/passwordless_spec.rb
spec/lib/workos/portal_spec.rb
spec/lib/workos/sso_spec.rb
spec/spec_helper.rb
spec/support/shared_examples/client_spec.rb

`Net::HTTP` [is not thread safe](https://stackoverflow.com/questions/3063088/is-rubys-nethttp-threadsafe), therefore memoization will potentially lead to issues when the code is run in a multi threaded environment (e.g Puma server with multiple workers). 
This PR amends the Client behaviour to return a new instance of `Net::HTTP` on each request.

Fix Thread Safety Issues with `Net::HTTP`

---

lib/workos/connection.rb
lib/workos/directory.rb
lib/workos/profile.rb
lib/workos/types/connection_struct.rb
lib/workos/types/directory_struct.rb
lib/workos/types/profile_struct.rb

This PR makes the `organization_id` field nullable on the following objects in preparation for future changes:
- `Connection`
- `Directory`
- `Profile`
This is a breaking change, so we'll need to bump the major version.
Resolves SDK-309.

Make `organization_id` nullable

---

lib/workos/webhooks.rb
spec/lib/workos/webhooks_spec.rb

@adamzinder found an issue with how the Time was being generated from the extracted timestamp, resulting in a bug in the tolerance check.
This PR is to fix that bug and deal with Time appropriately with the timestamp and tolerance check.

Fix bug in webhook tolerance check

---

lib/workos/webhooks.rb

Noticed that we were losing some type-safety due to the usage of `T.untyped`. Sorbet has support for [Tuple types](https://sorbet.org/docs/tuples), so we can use that instead here.
This shouldn't affect the runtime behavior.

Add full type for `get_timestamp_and_signature_hash`

---

.semaphore/semaphore.yml

Simplifies our Semaphore jobs that test backwards compatibility by using the [`matrix` option](https://docs.semaphoreci.com/essentials/build-matrix/) under `jobs`.

Simplify test jobs using `matrix`

---

lib/workos/types/passwordless_session_struct.rb

was putzing around with workos in IRB and it exploded due to `Date` being uninitialized...seems like we're missing a require somewhere?  sinatra pulls this in, and many other gems, so this issue does not always present.  repro steps below
```ruby
irb
> require 'workos'
true
> WorkOS::Types::PasswordlessSessionStruct
Traceback (most recent call last):
... 10 levels...
5: from /Users/daniel.pepper/code/workos/sdk-ruby/lib/workos/types.rb:14:in `<module:Types>'
4: from /Users/daniel.pepper/code/workos/sdk-ruby/lib/workos/types.rb:14:in `require_relative'
3: from /Users/daniel.pepper/code/workos/sdk-ruby/lib/workos/types/passwordless_session_struct.rb:6:in `<top (required)>'
2: from /Users/daniel.pepper/code/workos/sdk-ruby/lib/workos/types/passwordless_session_struct.rb:7:in …
```

uninitialized constant

---

Gemfile.lock
lib/workos/version.rb

Includes fixes from #148 and #152 to address the issue brought up in https://github.com/workos/workos-ruby/issues/147 (and a couple of other PR's that have come in since we'd released 2.2.0)

Create 2.2.1 version of the workos gem

---

lib/workos/challenge.rb
lib/workos/types/challenge_struct.rb
spec/support/fixtures/vcr_cassettes/mfa/challenge_factor_totp_valid.yml

Require `expires_at` to no be null for authentication challenge in MFA API

Require expires_at to not be null for authentication challenge

---

lib/workos/client.rb
spec/support/shared_examples/client_spec.rb

`write_timeout` is only supported for Ruby version 2.6.0+ so we should check that before setting in order to make the gem backwards compatible for older Ruby versions.

Only set write_timeout if Ruby version is greater or equal to 2.6.0

---

lib/workos.rb
lib/workos/audit_log_export.rb
lib/workos/audit_logs.rb
lib/workos/client.rb
lib/workos/errors.rb
lib/workos/types.rb
lib/workos/types/audit_log_export_struct.rb
spec/lib/workos/audit_logs_spec.rb
spec/support/fixtures/vcr_cassettes/audit_logs/create_event.yml
spec/support/fixtures/vcr_cassettes/audit_logs/create_event_custom_idempotency_key.yml
spec/support/fixtures/vcr_cassettes/audit_logs/create_event_invalid.yml
spec/support/fixtures/vcr_cassettes/audit_logs/create_export.yml
spec/support/fixtures/vcr_cassettes/audit_logs/create_export_with_filters.yml
spec/support/fixtures/vcr_cassettes/audit_logs/get_export.yml

Adds `create_event`, `create_export` and `get_export` methods.
Note: currently includes the changes from https://github.com/workos/workos-ruby/pull/174

Add AuditLogs module

---

Gemfile.lock
lib/workos/version.rb

Bump the gem version to 2.11.0.
```
[ ] Yes
```

Bump version to v2.11.0

---

lib/workos/client.rb

Resolves https://github.com/workos/workos-ruby/issues/190
```
[ ] Yes
```

Add Generic Default Error to Response Handler

---

spec/lib/workos/event_spec.rb
spec/support/fixtures/vcr_cassettes/events/list_events_with_range.yml

Use snake case for range params in the Events API. This makes Events consistent with the rest of our API.
```
[ ] Yes
```

Use snake case for Events range params

---

.rubocop.yml
lib/workos/audit_logs.rb
lib/workos/directory_user.rb
lib/workos/mfa.rb
lib/workos/sso.rb
lib/workos/webhooks.rb
spec/lib/workos/audit_logs_spec.rb
spec/support/fixtures/vcr_cassettes/audit_logs/create_export_with_filters.yml

Adds `actor_ids` / `actor_names` and deprecates `actors`
```
[X] Yes
```

add `actor_ids` param to `create_export`

---

lib/workos/version.rb

* Changed the Events API (in beta) `rangeStart` and `rangeEnd` parameters to `range_start` and `range_end` (https://github.com/workos/workos-ruby/pull/200).
* Added `actor_ids`, and `actor_names` parameters to `auditLogs.createExport` method, deprecated `actors` (https://github.com/workos/workos-ruby/pull/197).
```
[ ] Yes
```

Update version to v2.15.0

---

lib/workos/version.rb

- Use `list_metadata` instead of `listMetadata` in the `Events` API
```
[ ] Yes
```

Update version to 2.16.0

---

lib/workos.rb
lib/workos/client.rb
lib/workos/configuration.rb
lib/workos/sso.rb
spec/lib/workos/sso_spec.rb

Previously, we were grabbing the value of the `WORKOS_API_HOSTNAME` and `WORKOS_API_KEY` env vars at compile time. For folks using something like dotenv, if dotenv wasn't being loaded before WorkOS then the WorkOS gem wouldn't see the env vars later set by dotenv.
Using lazy loading here helps to ensure that we only capture the environment variables when we actually need them.
```
[ ] Yes
```

Lazily load configuration env vars

---

lib/workos.rb
lib/workos/magic_auth_challenge.rb
lib/workos/types.rb
lib/workos/types/magic_auth_challenge_struct.rb
lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/send_magic_auth_code/valid.yml

* Creates a one-time Magic Auth code and emails it to the user.
```
[ ] Yes
```

Add send_magic_auth_code method to UserManagement module

---

lib/workos/types/user_struct.rb
lib/workos/user.rb
lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/add_user_to_organization_valid.yml
spec/support/fixtures/vcr_cassettes/user_management/confirm_password_reset/valid.yml
spec/support/fixtures/vcr_cassettes/user_management/create_password_reset_challenge/valid.yml
spec/support/fixtures/vcr_cassettes/user_management/create_user_valid.yml
spec/support/fixtures/vcr_cassettes/user_management/get_user.yml
spec/support/fixtures/vcr_cassettes/user_management/list_users/no_options.yml
spec/support/fixtures/vcr_cassettes/user_management/list_users/with_options.yml
spec/support/fixtures/vcr_cassettes/user_management/remove_user_from_organization_valid.yml
spec/support/fixtures/vcr_cassettes/user_management/verify_email/valid.yml

* Rename email_verified_at to email_verified and change it to a boolean.
* Remove all *_profile_id fields.
* Remove user_type field from User.
* Remove type argument from list_users.
```
[ ] Yes
```

Bring User in line with current API

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb

Changes authenticate_user_password client_id param to non-nilable and remove logging statements
```
[ ] Yes
```

Change authenticate_user_password client_id param to non-nilable and remove logging statements

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/authenticate_user_magic_auth/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_user_magic_auth/valid.yml

Adds authenticate_user_magic_auth, tests, and fixtures.
```
[ ] Yes
```

Add authenticate_user_magic_auth method to UserManagement module

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/authenticate_user_with_code/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_user_with_code/valid.yml

Adds authenticate_user_with_code, tests, and fixtures.
```
[ ] Yes
```

Add authenticate_user_with_code method to UserManagement module

---

lib/workos.rb
lib/workos/authentication_factor_and_challenge.rb
lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/enroll_auth_factor/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/enroll_auth_factor/valid.yml
spec/support/fixtures/vcr_cassettes/user_management/list_auth_factors/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/list_auth_factors/valid.yml

Add endpoints for 
1) `enroll_auth_factor` to enroll a user in an auth factor
Introduces a joint object `AuthenticationFactorAndChallenge` for the response 
2) `list_auth_factors` to list a user's auth factors. 
```
[ X ] Yes
```

Add endpoints for creating and listing auth factors

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/send_password_reset_email/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/send_password_reset_email/valid.yml

Fixes USRLD-1088
Fixes USRLD-1095
1) Rename `confirm_password_reset` to `reset_password` (note: the payload already returned {user: `user`, token: `token`})
2) Rename `create_password_reset_challenge` to `send_password_reset_email` 
```
[ X ] Yes
```

Rename password specific endpoints

---

Gemfile.lock

Had to run `bundle update --patch sorbet` to update `sorbet`, since we were having issues when running `bundle install`:
````
Your lockfile was created by an old Bundler that left some things out.
Because of the missing DEPENDENCIES, we can only install gems one at a time, instead of installing 8 at a time.
You can fix this by adding the missing gems to your Gemfile, running bundle install, and then removing the gems from your Gemfile.
The missing gems are:
* sorbet-static depended upon by sorbet
* sorbet-static depended upon by tapioca
````
```
[ ] Yes
```
If yes, link a related docs PR and add a docs maintainer as a reviewer. Their approval is …

Bundle update `sorbet`

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/send_magic_auth_code/valid.yml

- Updates `send_magic_auth_code` to send `email` instead of deprecated `email_address`
- Updates route to `user_management/magic_auth/send`
- Updates test
```
[ ] Yes
```

Update `send_magic_auth_code` method according to latest API reference

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/send_verification_email/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/send_verification_email/valid.yml
spec/support/fixtures/vcr_cassettes/user_management/verify_email/invalid_code.yml
spec/support/fixtures/vcr_cassettes/user_management/verify_email/invalid_magic_auth_challenge.yml
spec/support/fixtures/vcr_cassettes/user_management/verify_email/valid.yml

- Re-order methods according to API reference 
- Update `send_verification_email` and `verify_email` methods 
```
[ ] Yes
```

Refactor Email Verification methods according to latest API reference

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/confirm_password_reset/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/reset_password/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/reset_password/valid.yml
spec/support/fixtures/vcr_cassettes/user_management/send_password_reset_email/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/send_password_reset_email/valid.yml

Refactoring `send_password_reset_email` & `reset_password` + updating tests
```
[X] Yes
```

Update Password Reset methods according to latest API reference

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_magic_auth/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_magic_auth/valid.yml

- Updates the `authenticate_with_magic_auth` to receive `email` instead of `user_id` 
- Updates tests
```
[X] Yes
```

Update `authenticate_with_magic_auth` to use the `email` instead of `user_id` parameter

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb

Add password, password_hash and password_hash_type to UserManagement.update_user function
https://workos.com/docs/reference/user-management/user/update
```
[ ] Yes
```

Add password, password_hash and password_hash_type to update_user 

---

lib/workos.rb
lib/workos/authentication_response.rb
lib/workos/user_management.rb

Return AuthenticationReponse instead of UserResponse to surface optional organization_id
```
[ ] Yes
```

Return AuthenticationReponse instead of UserResponse to surface optional organization_id

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/send_magic_auth_code/valid.yml

Usermanagement send_magic_auth_code does not return a user anymore
See api reference documentation, https://workos.com/docs/reference/user-management/magic-auth
```
[ ] Yes
```

Usermanagement send_magic_auth_code does not return a user anymore

---

lib/workos/types/user_struct.rb
lib/workos/user.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/get_user.yml

Adds the new `profile_picture_url` field to the Ruby SDK `User` object.
```
[x] Yes
```

Add `profile_picture_url` attribute to the `User` object

---

lib/workos.rb
lib/workos/authentication_response.rb
lib/workos/impersonator.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_code/valid_with_impersonator.yml

Adds Impersonation-related fields to the authentication response class.
```
[ ] Yes
```

Add `impersonator` attr to `AuthenticationResponse`

---

lib/workos.rb
lib/workos/refresh_authentication_response.rb
lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/spec_helper.rb
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_code/valid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_email_verification/valid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_magic_auth/valid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_organization_selection/valid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_password/valid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_refresh_code/invalid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_refresh_token/valid.yml
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_totp/valid.yml

Add session-related endpoints

---

.github/workflows/ci.yml

We are working on consolidating all CI to GitHub Actions.
```
[ ] Yes
```

Migrate repo to use GitHub Actions

---

.github/workflows/release.yml

This is migrating our release process from Semaphore to GitHub Actions.
```
[ ] Yes
```

Build and push new releases to RubyGems automatically

---

.github/workflows/release.yml

This should fix our release workflow https://github.com/workos/workos-ruby/actions/runs/8622607640/job/23634086661
```
[ ] Yes
```

Ensure the .gem directory exists for the rubygems credentials

---

lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/revoke_session/not_found.yml
spec/support/fixtures/vcr_cassettes/user_management/revoke_session/valid.yml

We should have been passing `auth: true` in order authorization headers to be included in the request. Since this method was already broken and would have never returned successfully, I also updated it to return a boolean like our other methods which where the API doesn't have a meaningful response payload.
```
[ ] Yes
```

Fix `revoke_session` by including authorization headers

---

Gemfile.lock
lib/workos.rb
lib/workos/client.rb
lib/workos/errors.rb
spec/lib/workos/client.rb
spec/lib/workos/directory_sync_spec.rb
spec/lib/workos/mfa_spec.rb
spec/lib/workos/organizations_spec.rb
spec/lib/workos/passwordless_spec.rb
spec/lib/workos/sso_spec.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/base/execute_request_unauthenticated.yml

- Adds new error types to be more specific
- Adds data to 400 error responses so users can find out exactly what went wrong
```
[ ] Yes
```

Add new error types and add data to error response

---

lib/workos/events.rb
spec/lib/workos/event_spec.rb
spec/support/fixtures/vcr_cassettes/events/list_events_with_after.yml
spec/support/fixtures/vcr_cassettes/events/list_events_with_no_options.yml
spec/support/fixtures/vcr_cassettes/events/list_events_with_range.yml

Make events parameter required for list_events.
```
[ ] Yes
```

Make events parameter required for list_events

---

lib/workos/organizations.rb

Marks `allow_profiles_outside_organization` as now deprecated. Also includes a few other misc. fixes:
* We missed adding `domain_data` as a parameter to `update_organization`, despite it being documented.
* We were always serializing certain parameters as `null` in the request body, even when the value is not passed.
```
[ ] Yes
```

Mark `allow_profiles_outside_organization` as deprecated

---

Gemfile.lock
lib/workos/organizations.rb
lib/workos/version.rb
spec/lib/workos/organizations_spec.rb
spec/support/fixtures/vcr_cassettes/organization/update_without_name.yml

- Make name optional when updating an Organization
```
[ ] Yes
```

Make name optional when updating an Organization

---

lib/workos/user_management.rb

Adds support for the optional `organization_id` parameter for use with the `refresh_token` grant type.
```
[ ] Yes
```

Add `organization_id` parameter to `authenticate_with_refresh_token`

---

lib/workos/types/provider.rb
lib/workos/user_management.rb
spec/lib/workos/sso_spec.rb
spec/lib/workos/user_management_spec.rb

This may be me completely understanding this code but: this looked like an omission here so I thought I'd open a PR for discussion.
```
[ ] Yes
```

Add Apple to list of providers.

---

lib/workos/types/intent.rb
spec/lib/workos/portal_spec.rb
spec/support/fixtures/vcr_cassettes/portal/generate_link_certificate_renewal.yml

Adding the certificate renewal intent as an option for link generation
```
[ ] Yes
```

Add certificate renewal intent

---

Gemfile.lock
lib/workos/version.rb

Adds:
- https://github.com/workos/workos-ruby/pull/326
```
[ ] Yes
```

Bump version to v5.6.0

---

lib/workos.rb
lib/workos/types.rb
lib/workos/types/widget_scope.rb
lib/workos/widgets.rb
spec/lib/workos/widgets_spec.rb
spec/support/fixtures/vcr_cassettes/widgets/get_token.yml
spec/support/fixtures/vcr_cassettes/widgets/get_token_invalid_organization_id.yml
spec/support/fixtures/vcr_cassettes/widgets/get_token_invalid_user_id.yml

Add get widget token API support.
```
[ ] Yes
```

Add get widget token API support

---

lib/workos.rb
lib/workos/organizations.rb
lib/workos/role.rb
spec/lib/workos/organizations_spec.rb
spec/support/fixtures/vcr_cassettes/organization/list_organization_roles.yml

Add GET /organization/:orgId/roles support.
```
[ ] Yes
```

Add GET /organization/:orgId/roles support

---

lib/workos.rb
lib/workos/client.rb
lib/workos/errors.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_password/unverified.yml

Fixes https://github.com/workos/workos-ruby/issues/263
Adds a new `ForbiddenRequestError` type for 403 responses from the API.
```
[ ] Yes
```

Add new ForbiddenRequestError

---

Gemfile.lock
lib/workos/version.rb

Bump to version 5.10.0.
```
[ ] Yes
```

Bump to version 5.10.0

---

lib/workos/session.rb
lib/workos/user_management.rb
spec/lib/workos/session_spec.rb
spec/lib/workos/user_management_spec.rb

Adds a new optional `return_to` parameter to `UserManagement.get_logout_url` to support the upcoming Logout URIs feature.
```
[ ] Yes
```

Add `return_to` param to `UserManagement.get_logout_url`

---

lib/workos.rb
lib/workos/cache.rb
lib/workos/session.rb
spec/lib/workos/cache_spec.rb
spec/lib/workos/session_spec.rb

This PR adds a cache module and tests, and then uses that to cache the return value of fetching JWKS per `client_id`.
```
[ ] Yes
```
Fixes #334

Add caching to remote JWKS fetch

---

lib/workos/types/intent.rb
spec/lib/workos/portal_spec.rb
spec/support/fixtures/vcr_cassettes/portal/generate_link_domain_verification.yml

Adding the domain verification intent as an option for admin portal link generation
```
[ ] Yes
```

Add domain verification intent in admin portal link generation

---

lib/workos/user.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/get_user.yml

https://linear.app/workos/issue/AUTH-4177/update-workos-ruby-sdk-for-last-sign-in-at
adds `last_sign_in_at` to user
```
[X] Yes
```
docs PR: https://github.com/workos/workos/pull/35170

add last_sign_in_at to user

---

lib/workos/directory_user.rb

Add email standard attribute to DirectoryUser and mark deprecated standard attributes.
```
[ ] Yes
```

Add email standard attribute to DirectoryUser and mark deprecated standard attributes

---

Gemfile.lock
lib/workos/version.rb

Bump to version 5.17.0.
```
[ ] Yes
```

Bump to version 5.17.0

---

Gemfile.lock

It is related to the security issue https://nvd.nist.gov/vuln/detail/CVE-2024-49761
```
[ ] Yes
```

Bump rexml from 3.2.6 to 3.4.1

---

lib/workos/user_management.rb

Add missing session param to authenticate methods.
`authenticate_with_password`
`authenticate_with_magic_auth`
`authenticate_with_organization_selection`
`authenticate_with_totp`
`authenticate_with_email_verification`
```
[ ] Yes
```

add missing session param to authenticate_with methods

---

lib/workos.rb
lib/workos/authentication_response.rb
lib/workos/oauth_tokens.rb
lib/workos/user_management.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/user_management/authenticate_with_code/valid_with_oauth_tokens.yml

- adds support for the `oauth_tokens` object in the authenticate API response
- adds support for the new `provider_scopes` query parameter
```
[X] Yes
```

add support for custom oauth scopes

---

Gemfile.lock
lib/workos/version.rb

version bump that includes:
- https://github.com/workos/workos-ruby/pull/379
```
[ ] Yes
```

bump to v5.20.0

---

lib/workos/organizations.rb
lib/workos/role.rb
spec/lib/workos/organizations_spec.rb
spec/lib/workos/role_spec.rb
spec/support/fixtures/vcr_cassettes/organization/list_organization_roles.yml

The API response for Roles now includes the permissions associated with that role. However, this has not been exposed in the ruby API. This commit fixes that problem.
```
[x] Yes
```

Add `permissions` to `Role`

---

lib/workos/sso.rb
spec/lib/workos/sso_spec.rb

Fixes the SSO module's error handling to surface detailed validation errors instead of swallowing them with generic "Something went wrong" messages.
**Problem**: The SSO `profile_and_token` method used custom error handling that bypassed the standard SDK error processing, converting detailed 422 validation errors into generic messages. This created poor developer experience when debugging OAuth code exchange failures.
**Solution**: Remove the custom error handling and use the standard `execute_request` method like all other SDK modules, which properly surfaces field-specific validation errors.
- Remove `check_and_raise_profile_and_token_error` method that was swallowing detailed errors
- Update `profile_and_token` to use `execute_request` instead of `client.request` 
- Leverage existing …

Fix SSO error handling to surface detailed validation errors

---

lib/workos/organization.rb
lib/workos/organizations.rb
lib/workos/user_management.rb
spec/lib/workos/organizations_spec.rb
spec/lib/workos/user_management_spec.rb
spec/support/fixtures/vcr_cassettes/organization/create_with_external_id.yml
spec/support/fixtures/vcr_cassettes/organization/update_with_external_id.yml
spec/support/fixtures/vcr_cassettes/organization/update_with_external_id_null.yml
spec/support/fixtures/vcr_cassettes/user_management/create_user_with_external_id.yml
spec/support/fixtures/vcr_cassettes/user_management/update_user_external_id_null.yml

On create and update (@mxlje already added to user update).
```
[ ] Yes
```

Add external_id to user and organization

---

Gemfile.lock
lib/workos/version.rb

Bump version due to changes in #381

bump to v5.23.0

---

lib/workos.rb
lib/workos/feature_flag.rb
lib/workos/organizations.rb
spec/lib/workos/organizations_spec.rb
spec/support/fixtures/vcr_cassettes/organization/list_organization_feature_flags.yml

Add GET /organizations/:orgId/feature-flags support
```
[x] Yes
```

Add GET /organizations/:orgId/feature-flags support
